typos: proposed revisions involving goeswith and Typo=Yes
UniversalDependencies/docs pull request #838
Opened 2022-01-15 02:37 UTC by nschneid

2022-01-29 01:14 UTC, nschneid commented
@dan-zeman Could you look this over? Trying to be as precise as possible about `goeswith` and `Typo=Yes`. (In our last meeting we agreed on the general contours but didn't discuss all the technicalities.)

2022-01-30 19:31 UTC, dan-zeman requested changes

2022-01-30 19:31 UTC, dan-zeman commented on _u-overview/typos.md
> +Parts attaching as `goeswith` should not themselves have any dependents, nor should they be included as nodes in [Enhanced Dependencies]().
Why not? I don't think we've discussed this. But enhanced dependencies have a very specific and relative small set of cases where basic dependencies are omitted, and this is definitely not among them. We also include punctuation in enhanced graphs, although it could be argued that punctuation nodes are not part of syntax. And if you disconnect a node from the enhanced graph, you will get an error message because the graph is not connected. Connectedness of the enhanced graph should be computable on the enhanced graph itself, without regard to the properties of the basic tree.

2022-01-30 19:31 UTC, dan-zeman commented on _u-overview/typos.md
> +- Any surface word attaching as `goeswith` in Basic Dependencies should have an orthographic form but empty lemma, UPOS of `X`, no morphological features (empty FEATS), and no Enhanced Dependencies (
Again, I disagree with the DEPS part.

(I'm also not sure why XPOS is allowed when FEATS are not, but that doesn't seem so important.)

2022-01-30 19:31 UTC, dan-zeman commented on _u-overview/typos.md
> +
I would remove DEPS from this example because enhanced dependencies are irrelevant to the treatment of typos and we don't have them in the other examples.

2022-01-30 19:37 UTC, nschneid commented on _u-overview/typos.md
> +Parts attaching as `goeswith` should not themselves have any dependents, nor should they be included as nodes in [Enhanced Dependencies]().
OK—I was thinking that "goeswith" reflects a surface relation and Enhanced aims for a deeper structure. But what about changing this to: "They should be included as nodes in Enhanced Dependencies but should not participate in any other enhanced relations besides the `goeswith` relation."?

2022-01-30 19:42 UTC, nschneid commented on _u-overview/typos.md
> +- Any surface word attaching as `goeswith` in Basic Dependencies should have an orthographic form but empty lemma, UPOS of `X`, no morphological features (empty FEATS), and no Enhanced Dependencies (
I went with `X` based on current conventions. I don't have a strong opinion regarding empty UPOS, but one consideration is that users may write tools to process just the token+UPOS information, and allowing empty UPOS where it is now required might break such tools.

2022-01-30 19:43 UTC, nschneid commented on _u-overview/typos.md
> +
OK

2022-01-30 21:20 UTC, amir-zeldes commented on _u-overview/typos.md
> +Parts attaching as `goeswith` should not themselves have any dependents, nor should they be included as nodes in [Enhanced Dependencies]().
Agreed with @dan-zeman - I would just keep goeswith the same, so that the set of tokens in the base tree is guaranteed to be connected and included in the enhanced tree. It's quite rare anyway, and the relation name itself tells you exactly what is going on, so it's worth keeping the data model mapping as simple as possible.

2022-01-30 21:22 UTC, amir-zeldes commented on _u-overview/typos.md
> +- Any surface word attaching as `goeswith` in Basic Dependencies should have an orthographic form but empty lemma, UPOS of `X`, no morphological features (empty FEATS), and no Enhanced Dependencies (
@dan-zeman XPOS has to be allowed since XPOS is governed by non-UD standards, which usually assign a tag to every token (or have to be allowed to do this in any case). I would also strongly prefer to have a filled UPOS - if something is a token, it should have a POS, and `X` is already the 'garbage can' category. Having a second non-POS ('empty') would just confuse things IMO, and `goeswith` already expresses that this token is just an orthographic artefact.

2022-01-30 21:24 UTC, dan-zeman commented on _u-overview/typos.md
> +Parts attaching as `goeswith` should not themselves have any dependents, nor should they be included as nodes in [Enhanced Dependencies]().
> They should be included as nodes in Enhanced Dependencies but should not participate in any other enhanced relations besides the `goeswith` relation.

Such a formulation seems uncontroversial.

2022-01-30 21:25 UTC, dan-zeman commented on _u-overview/typos.md
> +- Any surface word attaching as `goeswith` in Basic Dependencies should have an orthographic form but empty lemma, UPOS of `X`, no morphological features (empty FEATS), and no Enhanced Dependencies (
UPOS definitely should be `X`, as it is now. I was talking about XPOS.

2022-01-30 21:30 UTC, dan-zeman commented on _u-overview/typos.md
> +- Any surface word attaching as `goeswith` in Basic Dependencies should have an orthographic form but empty lemma, UPOS of `X`, no morphological features (empty FEATS), and no Enhanced Dependencies (
> XPOS has to be allowed since XPOS is governed by non-UD standards, which usually assign a tag to every token

Fair enough. But that would also mean that we should allow XPOS on the introductory line of multi-word tokens, which we currently don't.

2022-01-30 21:53 UTC, amir-zeldes commented on _u-overview/typos.md
> +- Any surface word attaching as `goeswith` in Basic Dependencies should have an orthographic form but empty lemma, UPOS of `X`, no morphological features (empty FEATS), and no Enhanced Dependencies (
> we should allow XPOS on the introductory line of multi-word tokens

No, I don't think we need to, since MWTs are UD concepts - they were introduced as such by the CoNLL-U format, so pre-UD language specific frameworks should not have xpos assignment guidelines for them (they are not tokens in that sense, they are a span annotation above tokens)

2022-01-30 22:25 UTC, nschneid commented on _u-overview/typos.md
> +- Any surface word attaching as `goeswith` in Basic Dependencies should have an orthographic form but empty lemma, UPOS of `X`, no morphological features (empty FEATS), and no Enhanced Dependencies (
Let's err on the side of not confusing people with a new rule here since XPOS is basically external to the UD guidelines. If a treebank wants to leave XPOS blank, I don't mind, but there may be good reason to keep the original tag.

2022-01-30 22:28 UTC, merged

2022-01-31 06:49 UTC, dan-zeman commented on _u-overview/typos.md
> +- Any surface word attaching as `goeswith` in Basic Dependencies should have an orthographic form but empty lemma, UPOS of `X`, no morphological features (empty FEATS), and no Enhanced Dependencies (
> > we should allow XPOS on the introductory line of multi-word tokens
> 
> No, I don't think we need to, since MWTs are UD concepts - they were introduced as such by the CoNLL-U format, so pre-UD language specific frameworks should not have xpos assignment guidelines for them (they are not tokens in that sense, they are a span annotation above tokens)

Maybe in English or Arabic; but in many languages, the new, UD-thing, is that these tokens are split into syntactic words, and in the pre-UD approach it is the multi-word token that is treated as one token. So the XPOS tagset actually has dedicated tags for them.

Anyway, this is off-topic, and I am also not trying to push through a new rule about it, it just struck me that it follows from the same argumentation as the XPOS for goeswith dependents.